### ISSUE TITLE
Where in the code does the extension block loading of video data?

### ISSUE THREAD

**Issue by sheddup** [Ashish-Bansal/audio-only-youtube#13]
after testing a few youtube videos I can see a couple megabytes of video/webm from googlevideo.com requests for each video that was watched, and I can't see any explicit blocking of the video urls inside the code.

**Comment by Ashish-Bansal** [comment]
Here every URL is processed : https://github.com/Ashish-Bansal/audio-only-youtube/blob/master/src/background.js#L104

Here we send message to the tab's content script to update video player's source : https://github.com/Ashish-Bansal/audio-only-youtube/blob/master/src/background.js#L104

When content script receives message here : https://github.com/Ashish-Bansal/audio-only-youtube/blob/master/src/audio-only-youtube.js#L14 we update video player's source.

Now instead of video it will load audio. Till the point of updating this source of the video player, yes video content will be downloaded but that's negligible compared to whole video.

**Comment by Ashish-Bansal** [comment]
Closing issue.
