### ISSUE TITLE
Work with embed's

### ISSUE THREAD

**Issue by Sikksens** [Ashish-Bansal/audio-only-youtube#2]
Hey there,

Great work on the extension, Just wanted to ask is it possible to get it to work on embedded youtube videos?

More specifically I was wondering if it's possible to disable the videos on sites like [https://www.dazik.com](https://www.dazik.com)

Thanks.

**Comment by Ashish-Bansal** [comment]
Hi @Sikksens, 

Fixed with 72ec9e0 commit!
But there might be regressions as now it would inject script to each and every page as well as frame. If this extension is enabled, it might disable video on that websites which are using adaptive streaming. Can you please test it ? 

Steps : 

1. Remove Audio Only Youtube extension from Chrome.
2. Download and unzip latest package
3. Open chrome://extensions and Click on "Load unpacked extensions"
4. Navigate to "src" folder in extracted folder.
5. Click on Select Extension folder.

**Comment by Sikksens** [comment]
You are amazing, working perfectly, thank you so much :D
