### ISSUE TITLE
I rewrite a similar extension, I am curious who is original author.

### ISSUE THREAD

**Issue by craftwar** [Ashish-Bansal/audio-only-youtube#22]
https://github.com/craftwar/youtube-audio
My work is based on https://github.com/animeshkundu/youtube-audio
It looks like his is similar to your.

**Comment by Ashish-Bansal** [comment]
Hi @craftwar,

Sorry for the late reply!

Yeah, I started this project in my college because I felt its need when I had bad internet connection at my home.

I just checked that project and he's clearly violating the license of this project. I wish he respected that. 

I also saw you have respected his work and giving him proper credits. Keep up great work! :)
I'm quite busy with office as well as personal life that I don't get free time to work on it. @sheldonled did full rewrite and but in that some old functionality was removed. One day I'm gonna look at it, fix and merge it. I wonder when that day's gonna come.

Anyway, Thanks for letting me know about it!
