### ISSUE TITLE
This extension saves bandwidth

### ISSUE THREAD

**Issue by eejdoowad** [Ashish-Bansal/audio-only-youtube#26]
EDIT: I earlier brashly declared that the extension should be unpublished because all it does is hide the youtube video's html element,  saving no bandwidth.

After testing with and without the extension and monitoring the Network tab, I've found that it does save bandwidth. Anecdotally, about 50%. Digging further into the source code, I see it works by intercepting and modifying requests for video data made by the browser.

My earlier claims that the extension saves no bandwidth are entirely false. Sorry. And thank you for the explanation.

**Comment by MiChAeLoKGB** [comment]
Thats weid, because it does work really well for me (even the mime type in requests changes to `audio/webm`).

Have you actually monitored the Network tab in Dev tools and compared it with & without this extension. Or did you just assume, without actually verifying what you said is true?

I was able to watch full 22 min. video with DevTools reporting 21.3 MB transferred (the stream itself, ignoring anything else) with this extension active. 
Watching same video without the extension, resulted to going over 24 MB transferred (again, only stream itself) after only first 4 minutes of the video were buffered...

Comparing that to the sizes reported by different "YouTube download" tools, they align quite well.

**Comment by Ashish-Bansal** [comment]
@eejdoowad If it's not working on specific kind of video, please post the link. Otherwise please provide  some proof to support your argument. Closing it for now.

**Comment by eejdoowad** [comment]
Sorry and thanks for the explanation @MiChAeLoKGB  and @Ashish-Bansal. I see it does save bandwidth.
