### ISSUE TITLE
Inquiry: Making a standalone YT audio player web app

### ISSUE THREAD

**Issue by zshanhui** [Ashish-Bansal/audio-only-youtube#59]
Hi, Ashish

Really appreciate your ground breaking work here and spend all night trying to understand how you did it because I would like to implement video stream blocking in a standalone web app that only streams audio from various video sites for a little side project.

I see that you achieve this via the `chrome.webRequest` API by blocking the video stream. Apparently you also remove the parameters: `['range', 'rn', 'rbuf']`, Is this what stops the video streams?

So, I understand the gist of how this works, but I don't have access to the Chrome ext APIs that you used. Was wondering if you have any ideas how to implement this in an web app scenario. I am planning to use the YT Iframe embedded API. Basically, I imagine that I would have to intercept the XMLHttpRequest made by the YT javascript library and then do something similar to what you did. I was looking at this library here: `https://github.com/jpillora/xhook` in order to intercept the YT requests.

Was wondering your thoughts on this and if this would work as a standalone implementation.

**Comment by Ashish-Bansal** [comment]
Hi @adrienshen,

Sorry, I rarely work on this project, so I probably missed your message while being busy with other stuff. Anyway, I don't know if it would really matter now but I would still add comments in case they do help you. 

I don't think it's possible to intercept requests sent by the iframes using any library (obviously unless you can modify js code running inside iframe itself.) -- otherwise wouldn't that be security vulnerability ?

So, even though I'm not familiar with it, I don't think you would be able to use xhook to build something like that. 

In case you really want to build web app, what you can do is move that audio stream extraction logic to server side. So, whenever user provides link to the page, you process that link server-side and use some pre-existing tool like youtube-dl to see if it can fetch you audio URLs or otherwise start up headless browser, intercept all request, get your result and send that back to the client. 

I'm closing this issue anyway. Let me know if you have any other questions.
